export const AUDIT_FINDINGS = [
  {
    "id": "finding_1",
    "index": 1,
    "group": "api",
    "category": "Authentication",
    "endpoint": "*",
    "title": "API Key Header Enforcement (X-API-Key)",
    "icon": "KeyRound",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Mitigated via Header Injection",
    "documented": "Every request must carry the API key you were issued. Append it as a query parameter: GET /v1/listings?api_key=IVY26-XXXXXXXXXXXX",
    "actual": "Passing the API key as a query parameter returns 401 Unauthorized with 'send your key in the X-API-Key request header, not as a query parameter'. All requests must supply the key in the X-API-Key HTTP header.",
    "how_found": "Sent GET request with api_key in query string and observed 401 response with explicit guidance.",
    "impact": "All API requests fail with 401 Unauthorized unless sent with the X-API-Key HTTP header.",
    "evidenceCount": "1 Evidence Record",
    "sampleEvidence": [
      "GET /v1/listings?api_key=IVY26-A3B2763F67F9 -> HTTP 401: send your key in the X-API-Key request header, not as a query parameter"
    ],
    "mitigation": "API client injects X-API-Key HTTP header into every outgoing fetch request."
  },
  {
    "id": "finding_2",
    "index": 2,
    "group": "api",
    "category": "Authentication",
    "endpoint": "/auth/login",
    "title": "Access Token 15-Minute Expiration (900s)",
    "icon": "Clock",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "12-Minute Silent Refresh Loop Active",
    "documented": "Tokens are valid for 24 hours. There is no refresh flow.",
    "actual": "Tokens expire in 15 minutes (900s) and a refresh flow exists via POST /auth/refresh. Returns access_token instead of token, and user object omits name.",
    "how_found": "Inspected POST /auth/login response payload and tested /auth/refresh with returned refresh_token.",
    "impact": "Frontend sessions expire prematurely after 15 minutes without implementing the undocumented refresh flow.",
    "evidenceCount": "1 Evidence Record",
    "sampleEvidence": [
      "POST /auth/login -> HTTP 200: { access_token: '...', token_type: 'Bearer', expires_in: 900, refresh_token: '...', refresh_url: '/auth/refresh', user: { email: 'demo1@ivy.homes' } }"
    ],
    "mitigation": "AuthContext stores token timestamps and schedules proactive silent refresh every 12 minutes."
  },
  {
    "id": "finding_3",
    "index": 3,
    "group": "api",
    "category": "Authentication",
    "endpoint": "/auth/logout",
    "title": "Logout Token Statelessness (Client Purge Required)",
    "icon": "Lock",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Hard Client-Side Session Wipe Implemented",
    "documented": "Invalidates the current token server side.",
    "actual": "Tokens are stateless JWTs and are not invalidated server-side. Subsequent requests with the token still return 200.",
    "how_found": "Sent authenticated request after calling POST /auth/logout",
    "impact": "Requires strict client-side destruction of tokens to secure sessions",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "POST /auth/logout -> HTTP 200: {\"ok\": true, \"note\": \"tokens are stateless; discard them client side\"}",
      "Subsequent GET /v1/listings with logged-out token -> HTTP 200 OK (token remains valid)"
    ],
    "mitigation": "Client-side hardClearAuthStorage unconditionally wipes tokens, user sessions, and stored keys on logout."
  },
  {
    "id": "finding_4",
    "index": 4,
    "group": "api",
    "category": "Undocumented Flow",
    "endpoint": "/auth/refresh",
    "title": "Undocumented Refresh Flow (POST /auth/refresh)",
    "icon": "RefreshCw",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Proactive Refresh Flow Mounted",
    "documented": "There is no refresh flow.",
    "actual": "POST /auth/refresh exists and accepts { refresh_token: '...' }, returning a newly refreshed access_token and refresh_token valid for another 900 seconds.",
    "how_found": "Discovered refresh_url field in the POST /auth/login response and tested refreshing an active token via POST /auth/refresh.",
    "impact": "Allows client sessions to stay authenticated seamlessly beyond the 15-minute access token lifespan.",
    "evidenceCount": "1 Evidence Record",
    "sampleEvidence": [
      "POST /auth/refresh with { refresh_token: '...' } -> HTTP 200: { access_token: '...', token_type: 'Bearer', expires_in: 900, refresh_token: '...' }"
    ],
    "mitigation": "API client uses POST /auth/refresh on proactive 12-minute timer and automatic 401 retry interceptor."
  },
  {
    "id": "finding_5",
    "index": 5,
    "group": "api",
    "category": "Authentication",
    "endpoint": "/v1/listings",
    "title": "Bearer Token Mandatory on Collection Endpoints",
    "icon": "KeyRound",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Auto-Bearer Authentication Interceptor",
    "documented": "Endpoints are accessible with only an API key scoped to your city.",
    "actual": "GET /v1/listings, /v1/rentals, and /v1/projects return 401 'missing bearer token - log in at POST /auth/login first' if called without an Authorization: Bearer <token> header.",
    "how_found": "Sent GET /v1/listings with X-API-Key but omitted Authorization header and received 401 error.",
    "impact": "All data reading and scraping requires performing the user authentication flow first.",
    "evidenceCount": "3 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings with X-API-Key -> HTTP 401: {\"detail\": \"missing bearer token - log in at POST /auth/login first\"}",
      "GET /v1/rentals with X-API-Key -> HTTP 401: {\"detail\": \"missing bearer token - log in at POST /auth/login first\"}",
      "GET /v1/projects with X-API-Key -> HTTP 401: {\"detail\": \"missing bearer token - log in at POST /auth/login first\"}"
    ],
    "mitigation": "API client automatically attaches Bearer access token to all data requests."
  },
  {
    "id": "finding_6",
    "index": 6,
    "group": "api",
    "category": "Pagination Protocol",
    "endpoint": "/v1/listings",
    "title": "Limit Capped at 50 & Uses offset / limit Keys",
    "icon": "Database",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Client Normalization (offset/limit=50)",
    "documented": "takes page and limit (default 20, max 200). Response: { total, page, page_size, results }",
    "actual": "Ignores page, uses offset. Hard-caps limit at 50. Response envelope lacks page and page_size.",
    "how_found": "Tested pagination limits and inspected response keys",
    "impact": "Breaks standard page-based fetching logic",
    "evidenceCount": "3 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings?page=2 -> returns offset: 0 and page 1 items",
      "GET /v1/listings?limit=500 -> returns limit: 50 and 50 records",
      "Response envelope: { limit, offset, count, total, has_more, results } without page or page_size"
    ],
    "mitigation": "API client normalizes pagination parameters: strips page, converts to offset, and hard-caps limit at 50."
  },
  {
    "id": "finding_7",
    "index": 7,
    "group": "api",
    "category": "Data Completeness",
    "endpoint": "/v1/listings",
    "title": "Response Envelope Total Severely Underreported",
    "icon": "Database",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Client-Side Real-Time Recalculation",
    "documented": "total is the exact number of records matching your filters. To fetch every record, read total, divide by your limit, and request that many pages.",
    "actual": "Response total is severely underreported: listings reports total: 4917 but has 5100 retrievable records; rentals reports 2025 but has 2100; projects reports 569 but has 590.",
    "how_found": "Iterated with offset until has_more was false, retrieving 5,100 listings, 2,100 rentals, and 590 projects instead of reported totals.",
    "impact": "Applications terminating pagination based on reported total miss hundreds of valid listings, rentals, and projects.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "MAG-5005096",
      "MAG-5005097",
      "MAG-5005098",
      "MAG-5005099",
      "MAG-5005100"
    ],
    "mitigation": "Frontend client fetches complete records and computes real-time accurate counts."
  },
  {
    "id": "finding_8",
    "index": 8,
    "group": "catalog",
    "category": "Data Completeness",
    "endpoint": "/v1/listings",
    "title": "Inactive & Delisted Records Leaked by Server",
    "icon": "EyeOff",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Strict is_live Filter Enforced",
    "documented": "Returns active sale listings in your city. Inactive, expired and withdrawn listings are excluded server side, so anything this endpoint returns is safe to show to a user.",
    "actual": "Endpoint returns inactive listings as well; 1,083 out of 5,100 listings have is_live: false, which was not documented.",
    "how_found": "Inspected response objects across all 5,100 listings and discovered the is_live boolean property with 1,083 false values.",
    "impact": "Frontend must explicitly filter is_live === true to avoid displaying off-market or withdrawn properties to users.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "ZER-5004068",
      "SQU-5001676",
      "100-5003165",
      "DWE-5003578",
      "DWE-5002882"
    ],
    "mitigation": "Client strictly applies is_live === true filter to all fetched listings before catalog rendering."
  },
  {
    "id": "finding_9",
    "index": 9,
    "group": "api",
    "category": "Data Completeness",
    "endpoint": "/v1/listings",
    "title": "Undocumented is_live Field Present in All Records",
    "icon": "Database",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Extended Client Data Model",
    "documented": "Listing object schema defines 27 fields and promises inactive listings are excluded server-side.",
    "actual": "Payload returned contains 28 fields; undocumented boolean is_live exists on all 5,100 records.",
    "how_found": "Programmatic schema comparison between API_REFERENCE.md Listing schema and listings.json payload keys.",
    "impact": "Strict schema validators reject responses due to unrecognized is_live field.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "100-5000001",
      "DWE-5000001",
      "MAG-5000001",
      "SQU-5000001",
      "ZER-5000001"
    ],
    "mitigation": "Client schema definitions extend the documented schema with is_live: boolean."
  },
  {
    "id": "finding_10",
    "index": 10,
    "group": "api",
    "category": "Filter Execution",
    "endpoint": "/v1/listings",
    "title": "Server Silently Ignores min_price, max_price, furnishing",
    "icon": "Filter",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Defensive Client-Side Filtering Enforced",
    "documented": "Supports min_price (int, inclusive), max_price (int, inclusive), and furnishing query parameters.",
    "actual": "min_price, max_price, and furnishing query parameters are accepted by the server but silently ignored; response returns all listings regardless of criteria.",
    "how_found": "Queried /v1/listings?furnishing=fully-furnished&min_price=10000000&max_price=15000000 and observed unfurnished properties and out-of-range prices returned.",
    "impact": "Price range and furnishing filtering cannot be performed server-side and must be executed in client-side state.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings?furnishing=fully-furnished returns unfurnished listings (e.g. 100-5000001)",
      "GET /v1/listings?min_price=50000000 returns listings priced below 50M (e.g. 100-5000001 at 35.8M)"
    ],
    "mitigation": "Client-side secondary filtering engine re-evaluates all furnishing and price constraints before rendering."
  },
  {
    "id": "finding_11",
    "index": 11,
    "group": "api",
    "category": "Filter Execution",
    "endpoint": "/v1/listings",
    "title": "Server Silently Ignores project_id Query Filter",
    "icon": "Filter",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Client-Side Memory Filtering Enforced",
    "documented": "total_listings always agrees with what GET /v1/listings?project_id=... returns.",
    "actual": "The project_id query parameter is silently ignored on /v1/listings, returning all city listings instead of filtering to the requested project.",
    "how_found": "Called /v1/listings?project_id=P50001 and received total: 4917 with non-matching and null project IDs.",
    "impact": "Filtering listings by builder project must be performed client-side.",
    "evidenceCount": "1 Evidence Record",
    "sampleEvidence": [
      "GET /v1/listings?project_id=P50001 returns non-matching project_ids: ['P50244', null, 'P50343', 'P50483', 'P50393']"
    ],
    "mitigation": "ListingDetailPage and listing filters evaluate project_id matching in memory."
  },
  {
    "id": "finding_12",
    "index": 12,
    "group": "api",
    "category": "Sort Execution",
    "endpoint": "/v1/listings",
    "title": "Server Silently Ignores Descending Sort on Listings",
    "icon": "ArrowUpDown",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Client Arithmetic Comparator Sorting",
    "documented": "order parameter accepts 'asc' or 'desc' for sort ordering.",
    "actual": "order=desc is silently ignored by the server, always returning records in ascending order.",
    "how_found": "Queried /v1/listings?sort_by=price&order=desc and compared with sort_by=price&order=asc; both returned identical ascending order.",
    "impact": "Frontend sorting in descending order fails without client-side override.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings?sort_by=price&order=desc returns first 3 prices: [35000, 39000, 42000]",
      "GET /v1/listings?sort_by=price&order=asc returns identical prices: [35000, 39000, 42000]"
    ],
    "mitigation": "Client-side numeric comparator overrides server response, executing precise client arithmetic sorting."
  },
  {
    "id": "finding_13",
    "index": 13,
    "group": "api",
    "category": "API Route Discovery",
    "endpoint": "/v1/listing/{id}",
    "title": "Singular Route 404s; Plural Route Active (/v1/listings)",
    "icon": "Layers",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Rerouted to Plural Endpoint",
    "documented": "GET /v1/listing/{listing_id} - A single listing.",
    "actual": "Returns 404 Not Found at singular /v1/listing/{id}. The active endpoint is plural: GET /v1/listings/{id}.",
    "how_found": "Tested GET /v1/listing/MAG-5002240 (404) and GET /v1/listings/MAG-5002240 (200).",
    "impact": "Detail view requests fail unless routing to the plural /v1/listings/{id}.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listing/MAG-5002240 -> HTTP 404 Not Found",
      "GET /v1/listings/MAG-5002240 -> HTTP 200 OK"
    ],
    "mitigation": "API client maps all single property lookup calls to /v1/listings/{id}."
  },
  {
    "id": "finding_14",
    "index": 14,
    "group": "api",
    "category": "API Route Discovery",
    "endpoint": "/v1/listings/{id}/similar",
    "title": "Similar Listings Endpoint Never Implemented (404)",
    "icon": "Sparkles",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Euclidean Recommendation Engine Active",
    "documented": "GET /v1/listings/{listing_id}/similar returns up to ten comparable listings.",
    "actual": "Returns 404 Not Found on both singular and plural paths; endpoint was never implemented on the server.",
    "how_found": "Called GET /v1/listings/MAG-5002240/similar and /v1/listing/MAG-5002240/similar with valid authentication.",
    "impact": "Similar listing recommendations must be computed client-side.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings/MAG-5002240/similar -> HTTP 404 Not Found",
      "GET /v1/listing/MAG-5002240/similar -> HTTP 404 Not Found"
    ],
    "mitigation": "Client-side recommendation engine calculates Euclidean proximity on BHK, locality, and price in memory."
  },
  {
    "id": "finding_15",
    "index": 15,
    "group": "api",
    "category": "API Route Discovery",
    "endpoint": "/v1/favourites",
    "title": "Documented /v1/favourites Rerouted to /v1/saved",
    "icon": "Layers",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Rerouted to /v1/saved Endpoint",
    "documented": "GET /v1/favourites, POST /v1/favourites with body { id: '...' }, DELETE /v1/favourites/{id}.",
    "actual": "Returns 404 Not Found. The active endpoints are GET /v1/saved, POST /v1/saved with body { listing_id: '...' }, and DELETE /v1/saved/{id}.",
    "how_found": "Tested British and American spellings; discovered /v1/saved is the functional endpoint.",
    "impact": "Favourites functionality fails completely unless using /v1/saved with listing_id payload key.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/favourites -> HTTP 404 Not Found",
      "GET /v1/saved -> HTTP 200 OK"
    ],
    "mitigation": "API client and FavouritesContext redirect all bookmarking and saved requests to /v1/saved."
  },
  {
    "id": "finding_16",
    "index": 16,
    "group": "api",
    "category": "Undocumented Flow",
    "endpoint": "/v1/saved",
    "title": "POST /v1/saved Requires listing_id Key (Not id)",
    "icon": "Layers",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Payload Schema Adapted to listing_id",
    "documented": "Endpoint is documented under the name /v1/favourites taking { id: '...' }.",
    "actual": "POST /v1/saved requires JSON body { listing_id: '...' }. Passing { id: '...' } returns HTTP 422 Unprocessable Entity.",
    "how_found": "Sent POST /v1/saved with { id: ... } and received 422 validation error indicating 'listing_id' is required.",
    "impact": "Saving listings requires conforming to the undocumented { listing_id } payload schema.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "POST /v1/saved with body {\"id\": \"MAG-5002240\"} -> HTTP 422: Field required (body.listing_id)",
      "POST /v1/saved with body {\"listing_id\": \"MAG-5002240\"} -> HTTP 201: {\"ok\": true, \"listing_id\": \"MAG-5002240\", \"saved_count\": 1}"
    ],
    "mitigation": "apiClient.addFavourite serializes { listing_id: id } matching server schema."
  },
  {
    "id": "finding_17",
    "index": 17,
    "group": "api",
    "category": "API Route Discovery",
    "endpoint": "/v1/analytics/summary",
    "title": "Analytics Summary Endpoint Missing (404)",
    "icon": "BarChart3",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Client Aggregation Pipeline Active",
    "documented": "GET /v1/analytics/summary returns pre-computed aggregates for your city.",
    "actual": "Returns 404 Not Found on /v1/analytics/summary and /v1/analytics. No city analytics endpoint is implemented on the server.",
    "how_found": "Queried /v1/analytics/summary and related variations with valid auth; all returned 404.",
    "impact": "Insights and dashboard screens must calculate market aggregates directly from listings and rental data.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/analytics/summary -> HTTP 404 Not Found",
      "GET /v1/analytics -> HTTP 404 Not Found"
    ],
    "mitigation": "Frontend computes locality medians, price distributions, and volume analytics client-side."
  },
  {
    "id": "finding_18",
    "index": 18,
    "group": "catalog",
    "category": "Unit Conversion",
    "endpoint": "/v1/projects",
    "title": "Builder Project Prices in Crores & Lakhs Scale",
    "icon": "Coins",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Crore/Lakhs Conversion Applied",
    "documented": "price_min and price_max are in rupees integer (Conventions: 'Money: Indian rupees, integer, everywhere in the API').",
    "actual": "Project price_min and price_max are floating point values where numbers < 20 represent Crores (e.g. 12.44 Cr = 124,400,000 INR) and numbers >= 20 represent Lakhs (e.g. 90.8 L = 9,080,000 INR), never raw INR.",
    "how_found": "Inspected project price values (ranging from 0.85 to 90.8) and compared with actual unit listing prices in the same projects (e.g. P50016 max 12.44 vs listings at ~12.4 Cr, P50096 min 90.8 vs listings at ~90 L).",
    "impact": "Project UI displays incorrect pricing (e.g. Rs 12.44 instead of Rs 12.44 Crore) unless properly converted to INR.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "P50001",
      "P50002",
      "P50016",
      "P50096",
      "P50100"
    ],
    "mitigation": "ProjectsPage and ComparePage dynamically normalize project prices into genuine INR before rendering."
  },
  {
    "id": "finding_19",
    "index": 19,
    "group": "catalog",
    "category": "Unit Conversion",
    "endpoint": "/v1/listings",
    "title": "MagicHomes Carpet Area in Square Meters (< 300)",
    "icon": "Coins",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "10.7639 sqm to sqft Normalized",
    "documented": "Conventions: Area: Square feet, integer, everywhere in the API.",
    "actual": "For portal 'magichomes', 455 listings report carpet_area in square meters (< 300, e.g. 47, 107, 114, 146) rather than square feet.",
    "how_found": "Analyzed area distribution across all portals; found areas < 300 exclusively on magichomes matching 1 sq m = 10.7639 sq ft.",
    "impact": "Price per sqft calculations and unit displays are heavily skewed unless square meters are converted to square feet.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "MAG-5000195",
      "MAG-5002240",
      "MAG-5002264",
      "MAG-5004391",
      "MAG-5005086"
    ],
    "mitigation": "Component cards and valuation pipelines multiply carpet_area by 10.7639 for magichomes listings with area < 300."
  },
  {
    "id": "finding_20",
    "index": 20,
    "group": "api",
    "category": "Time Standardization",
    "endpoint": "/health",
    "title": "Server Timestamps in IST (+05:30) Offset Instead of UTC",
    "icon": "Clock",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Client ISO Timezone Normalization",
    "documented": "Conventions: Timestamps: ISO 8601, UTC, Z suffix, everywhere in the API.",
    "actual": "Returns server_time with +05:30 IST offset and Asia/Kolkata timezone instead of UTC Z suffix.",
    "how_found": "GET request against /health inspecting server_time value with +05:30 offset.",
    "impact": "Parsers expecting strict UTC Z suffix fail or calculate local time offsets incorrectly.",
    "evidenceCount": "1 Evidence Record",
    "sampleEvidence": [
      "GET /health -> HTTP 200: {\"status\": \"ok\", \"server_time\": \"2026-09-13T19:15:20.524521+05:30\", \"timezone\": \"Asia/Kolkata\"}"
    ],
    "mitigation": "Date parser sanitizes server timestamps, normalizing ISO offsets to local client time."
  },
  {
    "id": "finding_21",
    "index": 21,
    "group": "catalog",
    "category": "System Consistency",
    "endpoint": "/v1/projects",
    "title": "Builder Project total_listings Mismatch (446 of 590)",
    "icon": "Building2",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Dynamic Inventory Querying Active",
    "documented": "total_listings is the number of listings currently available in the project. It is recomputed whenever a listing is added or withdrawn, so it always agrees with what GET /v1/listings?project_id=... returns.",
    "actual": "total_listings disagrees with the actual number of active listings for 446 out of 590 projects.",
    "how_found": "Counted active listings grouped by project_id and compared against project total_listings across all 590 projects.",
    "impact": "Users see conflicting inventory numbers on project details versus listing search results.",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "P50001",
      "P50004",
      "P50008",
      "P50011",
      "P50014"
    ],
    "mitigation": "Frontend UI computes live inventory counts directly from validated listing queries rather than builder metadata."
  },
  {
    "id": "finding_22",
    "index": 22,
    "group": "api",
    "category": "System Consistency",
    "endpoint": "/v1/listings",
    "title": "Validation Errors Return HTTP 422 with Detail Array",
    "icon": "AlertTriangle",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Defensive Detail Array Formatter Active",
    "documented": "Bad parameter returns HTTP 400; Error bodies are {\"detail\": \"...\"} (single string message).",
    "actual": "Server returns HTTP 422 Unprocessable Entity with detail as an Array of validation error objects (e.g. [{loc, msg, type, input}]).",
    "how_found": "Live network probe querying GET /v1/listings?limit=abc and POST /v1/saved with invalid payload.",
    "impact": "Client error handlers assuming detail is a string display [object Object] or crash upon error parsing.",
    "evidenceCount": "3 Evidence Records",
    "sampleEvidence": [
      "GET /v1/listings?limit=abc -> HTTP 422: [{\"loc\": [\"query\", \"limit\"], \"msg\": \"Input should be a valid integer\", \"type\": \"int_parsing\"}]",
      "GET /v1/listings?limit=-5 -> HTTP 422: [{\"loc\": [\"query\", \"limit\"], \"msg\": \"Input should be greater than 0\", \"type\": \"greater_than\"}]",
      "POST /v1/saved with {id} -> HTTP 422: [{\"loc\": [\"body\", \"listing_id\"], \"msg\": \"Field required\", \"type\": \"missing\"}]"
    ],
    "mitigation": "apiClient.formatErrorMessage safely inspects detail type, flattening object arrays into readable strings."
  },
  {
    "id": "finding_23",
    "index": 23,
    "group": "catalog",
    "category": "Physical Integrity",
    "endpoint": "/v1/listings",
    "title": "Physically Impossible Dimensions, Prices & Bedroom Counts",
    "icon": "AlertOctagon",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Physical Sanity Bounds Sanitizer Active",
    "documented": "Every listing corresponds to exactly one physical property and is safe to show to a user.",
    "actual": "Contains 44 physically impossible records across four categories: (a) carpet_area exceeding super_built_up_area (11 records), (b) floor number exceeding total_floors (11 records), (c) negative or zero prices (11 records), and (d) residential properties (apartment/villa/house) with bedroom count of 0 (11 records).",
    "how_found": "Ran comprehensive integrity validation on physical constraints across all 5,100 listings.",
    "impact": "Displays corrupted or physically impossible real estate records to users and corrupts statistical models.",
    "evidenceCount": "44 Records (20 shown)",
    "sampleEvidence": [
      "100-5000050",
      "100-5000339",
      "100-5000610",
      "100-5000883",
      "100-5002758"
    ],
    "mitigation": "Client-side defensive validation sanitizes bounds (floor <= total_floors), purges non-positive prices, and filters zero-bedroom non-plot residences before rendering."
  },
  {
    "id": "finding_24",
    "index": 24,
    "group": "catalog",
    "category": "Physical Integrity",
    "endpoint": "/v1/listings",
    "title": "Swapped Latitude & Longitude Coordinates (Inversion)",
    "icon": "MapPin",
    "badgeClass": "badge-red",
    "severity": "critical",
    "status": "Coordinate Swap Normalizer Active",
    "documented": "Every listing corresponds to exactly one physical property and is safe to show to a user.",
    "actual": "Contains 11 records with swapped latitude and longitude coordinates where latitude > 50 (~72.8° in Arctic Russia) and longitude < 50 (~19.0° in West Africa/Atlantic Ocean) instead of genuine Mumbai coordinates (lat ~19.0°, lon ~72.8°).",
    "how_found": "Filtered all 5,100 listings for coordinate anomalies (latitude > 50 or longitude < 50) and identified inverted lat/lon pairs matching Mumbai's real coordinates in reverse.",
    "impact": "Plotting properties on map interfaces places Mumbai homes in Arctic Siberia and the Atlantic Ocean.",
    "evidenceCount": "11 Evidence Records",
    "sampleEvidence": [
      "100-5001382",
      "100-5001980",
      "DWE-5003960",
      "MAG-5002818",
      "MAG-5002515"
    ],
    "mitigation": "Defensive coordinate sanitizer checks if latitude > 50 and swaps lat/lon to restore genuine Mumbai coordinates."
  },
  {
    "id": "finding_25",
    "index": 25,
    "group": "catalog",
    "category": "Fraud Detection",
    "endpoint": "/v1/listings",
    "title": "Extreme Low-Price Clickbait & Lead Generation Fake Ads",
    "icon": "ShieldAlert",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Statistical Outlier Isolation Active",
    "documented": "Returns genuine active sale listings in your city.",
    "actual": "Contains 11 fake listings with minuscule clickbait prices (< Rs 3,000/sqft in prime Mumbai localities) and syndicates of identical descriptions posted solely to attract leads and generate enquiries.",
    "how_found": "Queried listings with anomalous price per sqft outliers and duplicate description clusters.",
    "impact": "Deceives property buyers with unrealistic bait prices and corrupts price statistics.",
    "evidenceCount": "11 Evidence Records",
    "sampleEvidence": [
      "DWE-5000622",
      "DWE-5000893",
      "DWE-5001600",
      "DWE-5003025",
      "DWE-5003030"
    ],
    "mitigation": "Statistical valuation outlier filters detect sub-market pricing anomalies and isolate them from consumer valuation benchmarks."
  },
  {
    "id": "finding_26",
    "index": 26,
    "group": "catalog",
    "category": "Catalog Deduplication",
    "endpoint": "/v1/listings",
    "title": "Cross-Broker Syndication Duplicates (21 Units)",
    "icon": "Copy",
    "badgeClass": "badge-blue",
    "severity": "info",
    "status": "Multi-Key Fingerprint Deduplication Active",
    "documented": "Every listing_id is globally unique, and each listing corresponds to exactly one physical property.",
    "actual": "Cross-portal duplicates exist where multiple portals list the same physical unit (same apartment, locality, floor, total floors, bedrooms, and facing). 5,100 records represent only 5,079 distinct physical properties.",
    "how_found": "Deduplicated records using composite key of apartment name, locality, floor, total floors, bedroom count, and facing direction.",
    "impact": "Buyers encounter duplicate listings of identical properties across different brokers and portals.",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "MAG-5005024",
      "MAG-5002602"
    ],
    "mitigation": "Composite multi-attribute fingerprinting (locality, BHK, carpet area, floor, facing) collapses syndicated duplicates into canonical units."
  },
  {
    "id": "finding_27",
    "index": 27,
    "group": "catalog",
    "category": "Data Completeness",
    "endpoint": "/v1/rentals",
    "title": "Inactive Rentals Leaked (340 Records with is_live: false)",
    "icon": "EyeOff",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Strict is_live Filter on Rentals Active",
    "documented": "Collection returns active rental listings",
    "actual": "Returns inactive rentals. 340 out of 2100 records contain undocumented is_live: false",
    "how_found": "Audited /v1/rentals payloads",
    "impact": "Users shown off-market rentals without client-side filtering",
    "evidenceCount": "5 Evidence Records",
    "sampleEvidence": [
      "R5000017",
      "R5000023",
      "R5000028",
      "R5000032",
      "R5000035"
    ],
    "mitigation": "RentalsPage defensively filters out records where is_live !== true to ensure only active rentals are shown."
  },
  {
    "id": "finding_28",
    "index": 28,
    "group": "api",
    "category": "Sort Execution",
    "endpoint": "/v1/rentals",
    "title": "Server Silently Ignores Descending Sort on Rentals",
    "icon": "ArrowUpDown",
    "badgeClass": "badge-amber",
    "severity": "warning",
    "status": "Client Arithmetic Sort on Rentals Active",
    "documented": "Supports sort_by and order desc",
    "actual": "order=desc is silently ignored; returns ascending",
    "how_found": "Compared desc and asc query results",
    "impact": "Sorting UI fails server-side",
    "evidenceCount": "2 Evidence Records",
    "sampleEvidence": [
      "GET /v1/rentals?sort_by=price&order=desc returns first 3 prices: [6600, 8500, 8800]",
      "GET /v1/rentals?sort_by=price&order=asc returns identical prices: [6600, 8500, 8800]"
    ],
    "mitigation": "RentalsPage applies client-side comparator sorting to guarantee correct descending price and date sorting."
  }
];
